//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigatingMelbourne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI
    {
        public int Id { get; set; }
        public string AddressBlock { get; set; }
        public string StreetAddress { get; set; }
        public string AddressArea { get; set; }
        public string Name { get; set; }
        public string POIType { get; set; }
        public string SubType { get; set; }
        public string Location { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PlaceSeats { get; set; }
        public Nullable<int> POIYear { get; set; }
        public Nullable<bool> Popular { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
